"""empty message

Revision ID: 43a684ab9f79
Revises: None
Create Date: 2014-05-17 14:46:00.947716

"""

# revision identifiers, used by Alembic.
revision = '43a684ab9f79'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('password', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id2', sa.Integer(), nullable=True),
    sa.Column('author', sa.String(length=50), nullable=True),
    sa.Column('comment', sa.String(length=120), nullable=True),
    sa.Column('password', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('author'),
    sa.UniqueConstraint('comment')
    )
    op.create_table('entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=True),
    sa.Column('text', sa.String(length=120), nullable=True),
    sa.Column('password', sa.Integer(), nullable=True),
    sa.Column('etc', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entries')
    op.drop_table('comments')
    op.drop_table('logins')
    ### end Alembic commands ###
