"""empty message

Revision ID: 48bb84148a1
Revises: 44913d0260af
Create Date: 2014-05-10 15:02:21.254318

"""

# revision identifiers, used by Alembic.
revision = '48bb84148a1'
down_revision = '44913d0260af'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
